import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {Providers} from "./providers";
import { createClient } from "@/utils/supabase/server";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const supabase = await createClient()

  const { data, error } = await supabase.auth.getUser()

  let profileDiv = (<div></div>)
  if (error || !data?.user) {
    profileDiv = (
      <div>
        <Link prefetch={false} href="/login">Log in or sign up</Link>
      </div>
    );
  } else {
    profileDiv = (<div>
      <span>Logged in as</span> <Link prefetch={false} href="/profile" className="text-primary-800">{data.user.email}</Link><br />
      <Link prefetch={false} href="/logout" className="text-red-600">Sign out</Link>
    </div>);
  }
  //if (error || !data?.user) {
  //  redirect('/login')
  //}

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} dark antialiased`}
      >
        <Providers>
          <div className="min-h-screen">
            <div className="container mx-auto py-12">
              <div className="flex flex-row">
                <div>
                  <Link prefetch={false} href="/" className="text-3xl">LiquidCalc</Link>
                </div>
                <div className="basis-full grid grid-flow-col gap-5 mx-10">
                  <Link prefetch={false} href="/calculator" className="text-xl">Calculator</Link>
                  <Link prefetch={false} href="/liquids" className="text-xl">Liquids</Link>
                  <Link prefetch={false} href="/bases" className="text-xl">Bases</Link>
                  <Link prefetch={false} href="/flavours" className="text-xl">Flavours</Link>

                </div>
                <div>
                  {profileDiv}
                </div>
              </div>
            </div>
            {children}

          </div>
        </Providers>
      </body>
    </html>
  );
}
