name: Docker Build & Publish

on:
  push:
    branches: [main]

jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
      - name: Check out repository code 🛎️
        uses: actions/checkout@v4

      - name: Set up Docker Buildx 🚀
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub 🚢
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME}}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN}}

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.REPO_GITHUB_TOKEN }}

      - name: lowercase github.repository
        run: |
          echo "IMAGE_NAME=`echo ${{github.repository}} | tr '[:upper:]' '[:lower:]'`" >>${GITHUB_ENV}

      - name: create .env.local
        run: |
          echo "NEXT_PUBLIC_SUPABASE_URL=${{env.NEXT_PUBLIC_SUPABASE_URL}}" >> .env.local |
          echo "NEXT_PUBLIC_SUPABASE_ANON_KEY=${{env.NEXT_PUBLIC_SUPABASE_ANON_KEY}}" >> .env.local

          
      - name: Build and push 🏗️
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME}}/liquid-calculator:${{ github.sha }}
            ${{ secrets.DOCKER_HUB_USERNAME}}/liquid-calculator:latest
            ghcr.io/${{env.IMAGE_NAME}}:${{ github.sha }}
            ghcr.io/${{env.IMAGE_NAME}}:latest

